env:
  name: Pendulum-v0
solver:
  name: 'ddpg'
  gamma: 0.99
  tau: 0.001
  learning_rate_actor: 0.0001
  learning_rate_critic: 0.001
trainer:
  print_interval: 100
worker:
  print_interval: 1000
  exploration:
    name: 'ounoise'
    epsilon: 1,0.01,30000
replay_buffer:
  prioritized: True
  beta: 0.4,1,100000
  alpha: 0.6
  capacity: 100000